---

name: Feature request
title: '[FR] <REPLACE THIS WITH SOME MEANINGFUL TITLE OF THIS FEATURE REQUEST>'
labels: enhancement

body:
  - type: textarea
    id: desc
    attributes:
      label: What you miss in extendrom?
      description: "Describe your feature request as detailed as possible"
    validations:
      required: true
  - type: input
    id: vendor
    attributes:
      label: Device vendor
      description: What's your device vendor and model?
      placeholder: Google Pixel 7 Pro, OnePlus 6T, Sony xxx, ...
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Custom OS
      description: Custom OS name you build for
      placeholder: LOS, AXP.OS, AOSP, ... (add all that should apply)
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: OS version
      description: |
        What Android version this feature should support at minimum?
        Choose one or more but at least the one you currently build for as I might need your help for testing purposes.
      options:
       - label: Android 9
       - label: Android 10
       - label: Android 11
       - label: Android 12
       - label: Android 13
       - label: Android 14
       - label: Android 15
       - label: Yes, I have selected at least 1 Android version above
         required: true
  - type: textarea
    id: free
    attributes:
      label: Free form for additional info
      description: |
        **Note: do NOT add full log files within this issue!**
        Always use a paste service and/or for bigger logs it is strongly recommended using [github gists](https://gists.github.com).
      placeholder: "add any other info you might find useful to report, add screenshots or whatever helps ;)"
    validations:
      required: false
